// <auto-generated />
using System;
using Course_Test_Task;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Course_Test_Task.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230921140744_addMigr")]
    partial class addMigr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Course_Test_Task.Models.Catalog", b =>
                {
                    b.Property<int>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatalogId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCatalogId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CatalogId");

                    b.HasIndex("ParentCatalogId");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("Course_Test_Task.Models.Catalog", b =>
                {
                    b.HasOne("Course_Test_Task.Models.Catalog", "ParentCatalog")
                        .WithMany("SubCatalogs")
                        .HasForeignKey("ParentCatalogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentCatalog");
                });

            modelBuilder.Entity("Course_Test_Task.Models.Catalog", b =>
                {
                    b.Navigation("SubCatalogs");
                });
#pragma warning restore 612, 618
        }
    }
}
